language: python
cache: pip
dist: xenial
sudo: true

python:
- 3.5
- 3.7
- 3.8

env:
- DJANGO="django>=1.11.0,<1.12.0"
- DJANGO="django>=2.0,<2.1"
- DJANGO="django>=2.1,<2.2"
- DJANGO="django>=2.2,<2.3"
- DJANGO="django>=3.0,<3.1"
- DJANGO="django>=3.1,<3.2"

jobs:
  exclude:
  - python: 3.5
    env: DJANGO="django>=3.0,<3.1"
  - python: 3.5
    env: DJANGO="django>=3.1,<3.2"

services:
  - redis-server

before_install:
- pip install codecov

install:
- pip install -r requirements.txt
- travis_retry pip install $DJANGO

script:
- coverage run --rcfile=.coveragerc runtests.py

after_success:
- coverage report
- codecov

branches:
  only:
  - master
