language: python
cache: pip
python:
- 3.5

env:
- DJANGO="django>=1.11.0,<1.12.0"
- DJANGO="django>=2.0,<2.1"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      env:
	- DJANGO="django>=1.11.0,<1.12.0"
	- DJANGO="django>=2.0,<2.1"

services:
  - redis-server

before_install:
- pip install codecov

install:
- pip install -r requirements.txt
- travis_retry pip install $DJANGO

script:
- coverage run --rcfile=.coveragerc runtests.py

after_success:
- codecov

branches:
  only:
  - master